### PR TITLE
[PLib Options] Takes into account custom enum names

### PR DESCRIPTION
**Pull request by nidaren**
## Requested effect

I would like to kindly propose small change that would also fix feature request #403 .

This solution Enhances **options generator** to also take into account custom _Enum custom names_ provided via `EnumMember` attribute Value.

## Proposed fix

I have added extension method to `PLibCore` at `ExtensionMethods.cs`

```cs
        /// <summary>
        /// Returns enumeration value and considers custom value specified in EnumMemberAttribute if used.
        /// </summary>
        /// <param name="value">Enumeration to use.</param>
        /// <returns>Enumeration valule. If custom value was used via EnumMemberAttribute, it will return its value instead</returns>
        public static string GetEnumValue(this object value)
        {
            return ((EnumMemberAttribute)Attribute.GetCustomAttribute(value.GetType().GetFields(BindingFlags.Public | BindingFlags.Static)
            .Single(x => x.GetValue(null).Equals(value)), typeof(EnumMemberAttribute)))?.Value ?? value.ToString();
        }
```

Now with this change `GetEnumValue()` can be used on enumeration objects. If custom enum names were specified by the mod author, they will be used, if not the default string values.

I have applied this change to `EnumOption GetAttribute` in `SelectOneOptionsEntry.cs` and the system now works as expected.

```cs 
enumValue.GetEnumValue()
``` 

## Examples

Here is some example, let's assume the mod author specifies such enum:

```cs
[JsonConverter(typeof(StringEnumConverter))]
public enum ModTimeFormat
{
    [EnumMember(Value = "24-hour")]
    TwentyFour,
    [EnumMember(Value = "12-hour")]
    Twelve
}
```

This gets serialized by `StringEnumConverter` correctly and custom enum names are used.

Here is the generated json file:

```json
{
  "Status": 1,
  "TimeFormat": "24-hour"
}
```

However, in options within the game there are still the enum values used instead.

example from game as it is currently:
image

and here with my fix:
image

### CODE REVIEW

**Comment by peterhaneve** [comment]
Naming Enums in the options dialog can already be done with `[Option("Name")]` annotations on the enum members, or correctly named `STRINGS` entries. Does PLib really need a second, parallel method to do the same thing?

**Comment by nidaren** [comment]
> Naming Enums in the options dialog can already be done with `[Option("Name")]` annotations on the enum members, or correctly named `STRINGS` entries. Does PLib really need a second, parallel method to do the same thing?

Hello, thanks for your reply and looking into it.
I tried naming enum options in all of the available ways but the changes are not being picked up when in the menu. I went that route as EnumMember already exists and is correctly picked up by the serializer, hence it seemed logical.

**Comment by peterhaneve** [comment]
https://github.com/peterhaneve/ONIMods/blob/main/FastSave/FastSaveOptions.cs#L70 This method works for Fast Save

**Comment by nidaren** [comment]
> https://github.com/peterhaneve/ONIMods/blob/main/FastSave/FastSaveOptions.cs#L70 This method works for Fast Save

I checked it against my code and it did indeed work. I was sure I tried it and it did not do anything on enums, but it seems it does :) Apologies for the bother then, this can be closed.

**Pull request closed without merging**
