### PR TITLE
Changed build props to registry key values to better detect where ONI is installed and My Documents is located.

### PR DESCRIPTION
**Pull request by jasonolive**
Add conditionals to detect if One Drive is being used since My Documents gets relocated.

### CODE REVIEW

**Comment by peterhaneve** [comment]
Not all users who have OneDrive installed will have moved their Documents folder to it, so automatically changing the target will fail in those circumstances. The recommended approach for redirected documents folders is to use `Directory.Build.props.user` as described in the repository README and configuring a target path for dev mods to be installed.

Although the README states how to handle a nonstandard Oxygen Not Included install, it does not say anything about the Documents folder paths which can also be configured there. This would be a great documentation change!

**Comment by jasonolive** [comment]
That's a great point, I don't use OneDrive but I see a lot of people who's post-build copies it there.  I do wish MS would add that to a standard environment variable.

Which now has me thinking, we can just take the easy route.  Find all the values we need in the registry!

ONI Installation is at: HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Steam App 457140
My Documents is at: HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\User Shell Folders

**Comment by peterhaneve** [comment]
This method would fail on Linux and Mac systems that aim to build this mod (but, so would the current system most likely). The local override property solution is the most flexible way to handle any non standard scenario.

**Comment by jasonolive** [comment]
I agree, Mac and Linux users could still use the user prop file (theirs goes to a place similar to a Windows user appdata folder) but this will most likely cover every Windows user since these are the variables ONI would use internally.

**Comment by peterhaneve** [comment]
Your commits contain merge commits which will confuse the history if merged. Please either rebase your last commit onto a new branch based off of the current HEAD, or update your PR description to match your new changes so that I can squash the commits (as this will lose your commit message and replace it with the PR description).

**Comment by jasonolive** [comment]
Hope I did that right.  After having used SVN for the last 2 decades, I'm slowing getting on board the Git and GitHub train.

**Pull request merged**
