### PR TITLE
reduce idle movement of dupes/critters that are not visible

### PR DESCRIPTION
**Pull request by llunak**
Resubmit of #385 (which github doesn't allow to reopen because I've rebased it and force-pushed).

### CODE REVIEW

**Comment by peterhaneve** [comment]
This change would impact a number of evolution chamber builds that rely on them wandering into perilous situations and closing doors to trap them there.

Due to Klei making fairly decent improvements to critters in the next update, I do not think that this change would actually make a noticeable performance impact. How many us/1000ms does this shave off?

**Comment by llunak** [comment]
> How many us/1000ms does this shave off?

Quoting from #385 : "Reduces time spent in Navigator+StatesInstance from ~40ms to ~25 ms here". Since this is a resubmit, I don't have newer numbers.

> This change would impact a number of evolution chamber builds that rely on them wandering into perilous situations and closing doors to trap them there.

Yes, it would take longer for the critter to get trapped. Is that actually a problem? Besides, not everybody uses those, I don't.

> Due to Klei making fairly decent improvements to critters in the next update, I do not think that this change would actually make a noticeable performance impact. 

Does FastTrack already work with the beta? IIRC a significant cost was grubgrub handling, which the beta is supposed to improve, but I personally doubt the improvements would make this change not worth it.

**Comment by llunak** [comment]
With this [a.zip](https://github.com/peterhaneve/ONIMods/files/14541734/a.zip) save file, debug metrics say things like:
```
*s[351/83,063us|1/237us]
 Navigator+StatesInstance: 67,513us
 SegmentedCreature+Instance: 15,319us

```
When enabling the PR in my local mod:
```
*s[306/47,479us|1/155us]
 Navigator+StatesInstance: 39,858us
 SegmentedCreature+Instance: 7,401us

```

**Comment by peterhaneve** [comment]
It looks like you shaved about 35 ms / 1000 ms with this optimization, which places it correctly in the "Low" impact category. But since it could affect mature colonies, it should be disabled by default.

**Pull request merged**
